### ISSUE TITLE
Biztosításkötvény fajtái

### ISSUE THREAD

**Issue by danger97** [danger97/RFT_ZH#1]
A leírt biztosításkötvény fajtái nincsenek részletesen beimportálva.

- Életbiztosítás
- Utazási biztosítás
- Lakásbiztosítás
- Gépjármű-biztosítás
- Jogvédelmi biztosítás 

Kérem mi hamarabbi javítását!

**Comment by CaptainCandyyyyyy** [comment]
Feldolgozás alatt.

**Comment by actorvmi16** [comment]
Sikeresen javítva lett a hiba! @danger97

**Comment by danger97** [comment]
Sikeresen lezárom az issues-t! @CaptainCandyyyyyy @actorvmi16
